### ISSUE TITLE
Composer installer > 1.0.24 support

### ISSUE THREAD

**Issue by aimeos** [TYPO3/CmsComposerInstallers#108]
Aimeos has extensions itself and relies on composer/installers for installation in Laravel, Symfony and even TYPO3. This was OK because Aimeos extensions are supported by composer/installers:1.0.24 which is the only one accepted by this package.

Now, after composer 2.0 was released, we have the problem that composer 2.0 offers composer-plugin-api:2.0 which requires composer/installers:1.9 and there's no way to install the Aimeos TYPO3 extension via composer any more because of the version conflict for composer/installers.

What is the reason that the TYPO3 composer installers package restricts the composer/installers exactly to 10.24 and is there a way to update composer/installers to 1.9+?

**Comment by gilbertsoft** [comment]
The problem here is the support for TYPO3 which should be removed see discussion here https://github.com/composer/installers/pull/281 and https://github.com/composer/installers/pull/300
Newer versions if the installers allow to disable some of the delivered installation types but we were not able to get this working so far.

**Comment by helhum** [comment]
as pointed out, other versions of composer/installers break this installer. as long this is the case, the conflict has to stay.
