### ISSUE TITLE
Missing assets folder when creating public folder after installation

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/CmsComposerInstallers#142]
Given that:

1. I've created a TYPO3 extension as composer package
2. That extension does not have a `Public/` folder yet
3. The extension is installed
4. A new `Public/` folder is created within that extension 
5. The folder does not show up within `_assets/` folder

That might happen during setting up an extension, e.g. a sitepackage.

Workaround:

1. Remove the extension via `composer remove`
2. Re-Add the extension via `composer req`

Maybe we can ease that somehow? Provide a command or maybe "fix" that by a proper 404 handling within TYPO3 itself? I fear that many people will run into that issue when starting with v12.

**Comment by helhum** [comment]
Thanks for the report. 
Since the code that does the aaset publishing belongs to typo3 core, I suggest moving the report to forge. 

Some remarks on the current behaviour for clarification. 

1. Assets are published on "composer dump-autoload" as well. So no need to remove and add the extension after the folder is added
2. I'd say that the minimum requirement for an extension is to have two files: 1. composer.json, 2. Resources/Public/Icons/Extension.png. With this basic requirement fulfilled, there is no issue any more with asset publishing. 

But in any case the asset publishing process can and should be improved. Please file a forge ticket for that as pointed out above. 

Feel free to assign me to that forge ticket!

**Comment by DanielSiepmann** [comment]
Thanks for the fast response, I added a forge issue: https://forge.typo3.org/issues/100468
