### ISSUE TITLE
Option to deactivate the symlink creation on composer install

### ISSUE THREAD

**Issue by tliegl** [TYPO3/CmsComposerInstallers#21]
On some hosting providers (e. g. domainfactory) you can't create symlinks to files. So you have to copy the index.php into your web folder. When you then do a `composer install`, the file will get replaced with a symlink again.

So I think an option to deactivate this symlink creation would be very useful.

**Comment by helhum** [comment]
You can easily workaround this issue, by providing [composer scripts](https://getcomposer.org/doc/articles/scripts.md) which are executed after the plugin sets the symlinks.

But, yes, publishing options for that would be nice to have.

**Comment by tliegl** [comment]
Thank you for the hint to composer scripts. With that I could solve this problem simply like this:

    "scripts": {
      "post-update-cmd": [
        "php -r \"unlink('web/index.php');\"",
        "php -r \"copy('vendor/typo3/cms/index.php', 'web/index.php');\""
      ],
      "post-install-cmd": [
        "php -r \"unlink('web/index.php');\"",
        "php -r \"copy('vendor/typo3/cms/index.php', 'web/index.php');\""
      ]
    },

So after every `composer update` or `composer install` the symlink will get removed and replaced with a real copy of the index.php.

**Comment by mischka** [comment]
@helhum this should be a link to this post on https://wiki.typo3.org/Composer

**Comment by helhum** [comment]
@mischka you mean, this issue should be mentioned on the composer wiki page?

Go ahead, it is a Wiki page :)

**Comment by mischka** [comment]
@helhum Ok done

**Comment by Jabychan** [comment]
Even if you are able to remove the Symlink afterwards, would it not be better just to alert a warning "Symlink could not be established" instead of terminating the complete installation process.

Or using the Fallback Option in [Filesystem](https://github.com/TYPO3/CmsComposerInstallers/blob/master/Classes/TYPO3/CMS/Composer/Plugin/Util/Filesystem.php)->establishSymlinks() in the [CoreInstaller](https://github.com/TYPO3/CmsComposerInstallers/blob/master/Classes/TYPO3/CMS/Composer/Installer/CoreInstaller.php).

In my Case, I just want to use the Composer for the source management and I have no need for the symlinks. As I don't have administrator rights the process is always aborted.

**Comment by helhum** [comment]
this is solved now
