### ISSUE TITLE
Custom installation paths

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/CmsComposerInstallers#3]
Currently this plugin requires/enforces the following structure:

* `<path-to-document-root>`
    * `<document-root>`
        * `composer.json`
        * `typo3_src`
        * `typo3 -> typo3_src/typo3`
        * `index.php -> typo3_src/index.php`

The following structure would be quite useful instead:

* `<path-to-document-root>`
    * `composer.json`
    * `typo3_src`
    * `<document-root>`
        * `typo3 -> ../typo3_src/typo3`
        * `index.php -> ../typo3_src/index.php`

This keeps the publicly exposed data to a minimum but requires a different directory/symlink setup which could be achieved if the installation paths where configurable similar to [composer/installers](/composer/installers).

Please consider allowing custom installation paths.

**Comment by mblaschke** [comment]
+1

**Comment by Kitzberger** [comment]
:+1:

**Comment by utrotzek** [comment]
+1

**Comment by tmaroschik** [comment]
We want to allow more flexibility regarding the directory layout, but for this we need to refactor some things in the TYPO3 core to allow us so. We have a roadmap for that and started already some work in this direction.

I'll close this issue, because it's already on our agenda for the next version of this plugin.

**Comment by mbrodala** [comment]
@tmaroschik Looking forward to it. :-)
