### ISSUE TITLE
Replace index.php symlink with require

### ISSUE THREAD

**Issue by rvock** [TYPO3/CmsComposerInstallers#71]
Currently a symlink of index.php is created which points to the index.php in typo3-cms.

There are some hosts (e.g. DomainFactory) which generate a 500 Server Error for symlinked PHP files. The simple workaround is to use a require within a normal PHP file:

```php
<?php
require '../typo3_src/index.php';
```

**Comment by helhum** [comment]
This has been prepared with version 1.4 and will be fixed with TYPO3 9 (TYPO3 has become responsible for setting up the web directory)

However you can require helhum/typo3-composer-setup (https://github.com/helhum/typo3-composer-setup) for current typo3 version versions to already achieve the same now.
